/**
 * Antigravity Awesome Skills Catalog
 * Curated library of high-impact agentic playbooks and specialized SKILL.md bundles.
 */

import { SkillManifest } from "./skillRegistry";

export const AWESOME_SKILLS_CATALOG: SkillManifest[] = [
  {
    id: "perplexity-mcp-search",
    name: "Perplexity Real-Time Research (MCP)",
    category: "productivity",
    version: "2.1.0",
    description: "Perplexity Sonar-Pro live web research engine with direct URL source citations over Model Context Protocol.",
    author: "Perplexity AI",
    enabled: true,
    systemDirective: "Ground queries with real-time web search and output authoritative URL citations.",
    iconName: "Sparkles",
  },
  {
    id: "asi-evolve",
    name: "ASI-Evolve: AI Accelerates AI",
    category: "coding",
    version: "1.0.0",
    description: "Autonomous recursive self-evolution architecture: automated neural architecture search (NAS), optimizer discovery, and synthetic curriculum loops.",
    author: "Frontier AI Lab",
    enabled: true,
    systemDirective: "Design self-improving AI loops, autonomous NAS optimizations, and automated verifier-guided RLAIF architectures.",
    iconName: "TrendingUp",
  },
  {
    id: "lighthouse-attention",
    name: "Lighthouse Attention (Long Context)",
    category: "coding",
    version: "1.0.0",
    description: "Sub-quadratic O(N) hierarchical attention using periodic anchor landmarks for 1M-10M token context pre-training.",
    author: "Frontier AI Lab",
    enabled: true,
    systemDirective: "Implement O(N) landmark-based attention mechanisms, compressed KV-cache management, and long-context pre-training recipes.",
    iconName: "Layout",
  },
  {
    id: "mit-seal",
    name: "MIT SEAL (Self-Adapting Alignment)",
    category: "security",
    version: "1.0.0",
    description: "Test-time self-repair, adversarial self-probing, and orthogonal manifold projection to prevent catastrophic forgetting.",
    author: "MIT CSAIL",
    enabled: true,
    systemDirective: "Apply MIT SEAL test-time weight adaptation, non-destructive manifold projections, and self-diagnosing safety verifiers.",
    iconName: "ShieldAlert",
  },
  {
    id: "architect-mode",
    name: "Distributed Systems Architect",
    category: "coding",
    version: "2.4.0",
    description: "Evaluates CAP theorem tradeoffs, fault-tolerant microservice topologies, and event-driven architectures.",
    author: "Antigravity Awesome Skills",
    enabled: true,
    systemDirective: "Design distributed system architectures with explicit fault tolerance, caching, and scalability patterns.",
    iconName: "Layout",
  },
  {
    id: "clean-coder",
    name: "Clean Code & Refactoring",
    category: "coding",
    version: "1.8.0",
    description: "Applies strict SOLID principles, DRY standards, and eliminates cyclomatic code smells.",
    author: "Antigravity Awesome Skills",
    enabled: true,
    systemDirective: "Enforce clean modular architecture, single responsibility, and zero unnecessary code duplication.",
    iconName: "Palette",
  },
  {
    id: "devops-wizard",
    name: "DevOps & Infrastructure-as-Code",
    category: "productivity",
    version: "2.0.3",
    description: "Generates multi-stage Dockerfiles, Kubernetes manifests, and hardened GitHub Action CI/CD pipelines.",
    author: "Antigravity Awesome Skills",
    enabled: true,
    systemDirective: "Generate production-grade Dockerfiles, CI/CD workflows, and container configurations.",
    iconName: "TrendingUp",
  },
  {
    id: "database-tuning",
    name: "Database Query & Index Optimizer",
    category: "coding",
    version: "1.5.0",
    description: "Analyzes EXPLAIN execution plans, fixes N+1 query bugs, and recommends composite B-tree indexes.",
    author: "Antigravity Awesome Skills",
    enabled: true,
    systemDirective: "Optimize database schemas, eliminate N+1 queries, and design high-performance indexes.",
    iconName: "Activity",
  },
  {
    id: "pentest-security",
    name: "Offensive Security & Hardening",
    category: "security",
    version: "3.1.0",
    description: "Performs AST static analysis, JWT header tampering tests, and automated fuzzing audits.",
    author: "Antigravity Awesome Skills",
    enabled: true,
    systemDirective: "Audit code against offensive security attack vectors and generate hardened remediations.",
    iconName: "ShieldAlert",
  },
];
